'use strict';
// Generated by scripts/build-protocol.mjs from src/protocol.ts.
// Do not edit this file directly; edit src/protocol.ts and run npm run build:protocol.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/protocol.ts
var protocol_exports = {};
__export(protocol_exports, {
  CLI_CAPABILITIES: () => CLI_CAPABILITIES,
  COMMANDS: () => COMMANDS,
  DAEMON_CAPABILITIES: () => DAEMON_CAPABILITIES,
  EXTENSION_CAPABILITY_HINTS: () => EXTENSION_CAPABILITY_HINTS,
  LEGACY_ACTION_ALIASES: () => LEGACY_ACTION_ALIASES,
  PROTOCOL_VERSION: () => PROTOCOL_VERSION,
  ProtocolError: () => ProtocolError,
  RUNTIME_SCHEMA_VERSION: () => RUNTIME_SCHEMA_VERSION,
  createResultEnvelope: () => createResultEnvelope,
  mapNetworkCommand: () => mapNetworkCommand,
  normalizeCommand: () => normalizeCommand,
  normalizeRequest: () => normalizeRequest,
  protocolErrorFrom: () => protocolErrorFrom,
  validateRequest: () => validateRequest
});
module.exports = __toCommonJS(protocol_exports);
var PROTOCOL_VERSION = "2026-05-19";
var RUNTIME_SCHEMA_VERSION = "2026-05-20";
var CLI_CAPABILITIES = [
  "commandEnvelope",
  "doctorRuntimeDiagnostics",
  "staleDaemonShapeDiagnostics",
  "actionObservationRequest",
  "navigateFinalMetadata",
  "argsFile",
  "codeFile",
  "scroll",
  "clickProbe"
];
var DAEMON_CAPABILITIES = [
  "healthStatusRuntimeMetadata",
  "extensionHelloStorage",
  "actionObservation",
  "observe_start",
  "observe_diff",
  "artifactStore",
  "navigateFinalMetadataPassthrough",
  "get_text",
  "sessionNetworkCapture",
  "snapshotFilters",
  "clickProbe"
];
var EXTENSION_CAPABILITY_HINTS = [
  "navigateFinalMetadata",
  "observe_capture",
  "observe_start",
  "observe_diff",
  "network",
  "clickProbe",
  "cdpMouse",
  "cdpKeyboard",
  "cdpWheelScroll",
  "domPointer",
  "scroll",
  "get_text",
  "sessionNetworkCapture",
  "snapshotFilters"
];
var COMMANDS = {
  navigate: { required: ["url"], optional: ["newTab", "timeoutMs"] },
  find_tab: { required: [], optional: ["urlIncludes", "titleIncludes", "active", "tabId", "attach"] },
  snapshot: { required: [], optional: ["tabId", "maxDepth", "roles", "tags", "hasVisibleText", "textIncludes", "viewportOnly", "maxElements"], example: { tabId: 123, roles: ["button", "link"], hasVisibleText: true, maxElements: 50 } },
  click: {
    required: [],
    requiredOneOf: ["elementRef", "selector"],
    optional: ["elementRef", "selector", "tabId", "strategy", "force", "button", "clickCount", "modifiers", "expectChange", "observe", "observeNewTab", "expectNewTab"],
    example: { elementRef: "@e1jm0sbb_1", strategy: "auto", expectChange: true },
    strategies: ["auto", "cdp_mouse", "dom_pointer", "element_click"]
  },
  click_probe: {
    required: [],
    requiredOneOf: ["elementRef", "selector"],
    optional: ["elementRef", "selector", "tabId", "strategy", "force", "button", "clickCount", "modifiers", "observeNewTab", "expectNewTab", "waitMs", "filter", "includeHeaders", "includeBody", "redactSensitive", "maxRequests"],
    example: { elementRef: "@e1jm0sbb_1", strategy: "auto", filter: "/api/" },
    strategies: ["auto", "cdp_mouse", "dom_pointer", "element_click"]
  },
  fill: {
    required: ["value"],
    requiredOneOf: ["elementRef", "selector"],
    optional: ["elementRef", "selector", "tabId", "strategy", "clear", "commit", "expectChange", "observe"],
    strategies: ["native_setter", "text_input", "paste_like"]
  },
  press: {
    required: ["key"],
    optional: ["elementRef", "tabId", "selector", "strategy", "modifiers", "expectChange", "observe", "observeNewTab", "expectNewTab"],
    strategies: ["auto", "cdp_keyboard", "dom_keyboard"]
  },
  scroll: {
    required: [],
    optional: ["elementRef", "tabId", "selector", "strategy", "deltaX", "deltaY", "x", "y", "region", "steps", "block", "behavior", "waitMs"],
    example: { deltaY: 800, strategy: "dom" },
    strategies: ["auto", "dom", "wheel"]
  },
  select_option: { required: ["value"], requiredOneOf: ["elementRef", "selector"], optional: ["elementRef", "selector", "tabId"] },
  set_checked: { required: ["checked"], requiredOneOf: ["elementRef", "selector"], optional: ["elementRef", "selector", "tabId"] },
  wait_for: { required: [], optional: ["selector", "text", "state", "timeoutMs", "tabId", "expression"] },
  evaluate: { required: ["code"], optional: ["tabId"], example: { code: "return { title: document.title }" } },
  screenshot: { required: [], optional: ["tabId", "format", "quality", "fullPage", "file_name", "fileName"] },
  save_as_pdf: { required: [], optional: ["tabId", "paper_format", "landscape", "scale", "print_background", "file_name"] },
  observe_start: { required: [], optional: ["tabId", "mode", "baselineId", "includeNetworkMarker", "maxTextChars", "maxTextRuns"], example: { includeNetworkMarker: true } },
  observe_diff: { required: ["baselineId"], optional: ["tabId", "includeCurrent", "includeNetwork", "maxAdded", "maxRemoved", "maxSummaryChars", "allowStaleNavigationDiff"], example: { baselineId: "obs_...", includeNetwork: true } },
  network_start: { required: [], optional: ["filter", "tabId", "scope"], example: { scope: "session" } },
  network_list: { required: [], optional: ["filter", "sinceTimestampMs", "limit", "tabId", "method", "statusCode", "type"], example: { filter: "/api/" } },
  network_detail: { required: ["requestId"], optional: [], example: { requestId: "<id from network_list>" } },
  network_stop: { required: [] },
  upload: { required: ["files"], requiredOneOf: ["elementRef", "selector"], optional: ["elementRef", "selector", "tabId"] },
  download: { required: ["url"], optional: ["filename", "saveAs"] },
  get_text: { required: [], optional: ["tabId", "scope", "maxChars", "includeRuns", "selector"], example: { scope: "full", maxChars: 4e3, includeRuns: true } },
  list_tabs: { required: [] },
  close_tab: { required: [], optional: ["tabId"] },
  close_session: { required: [] }
};
var ELEMENT_REF_PATTERN = /^@e[^\s_]+_\d+$/;
var LEGACY_ACTION_ALIASES = {
  saveAsPdf: "save_as_pdf",
  selectOption: "select_option",
  setChecked: "set_checked",
  waitFor: "wait_for",
  findTab: "find_tab",
  getText: "get_text",
  clickProbe: "click_probe",
  networkStart: "network_start",
  networkList: "network_list",
  networkDetail: "network_detail",
  networkStop: "network_stop"
};
var ProtocolError = class extends Error {
  code;
  details;
  retryable;
  constructor(code, message, details = void 0, retryable = false) {
    super(message);
    this.name = "ProtocolError";
    this.code = code;
    this.details = details;
    this.retryable = retryable;
  }
};
function normalizeCommand(command) {
  return LEGACY_ACTION_ALIASES[command] || command;
}
function normalizeRequest(body = {}) {
  const rawCommand = body.command || body.action;
  let command = normalizeCommand(rawCommand);
  const args = body.args && typeof body.args === "object" ? body.args : {};
  const normalizedArgs = { ...args };
  if (rawCommand === "attach_tab" || rawCommand === "attachTab") {
    command = "find_tab";
    normalizedArgs.attach = true;
  }
  return {
    id: body.id || `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
    version: body.version || PROTOCOL_VERSION,
    session: body.session || "default",
    command,
    action: command,
    args: normalizedArgs,
    timeoutMs: Number.isFinite(body.timeoutMs) ? body.timeoutMs : 3e4
  };
}
function validateRequest(request) {
  if (!request.command) {
    throw new ProtocolError("VALIDATION_ERROR", "command/action is required", { field: "command" });
  }
  const spec = COMMANDS[request.command];
  if (!spec) {
    throw new ProtocolError("UNKNOWN_COMMAND", `Unknown command: ${request.command}`, {
      command: request.command,
      validCommands: Object.keys(COMMANDS)
    });
  }
  for (const field of spec.required) {
    if (request.args[field] === void 0 || request.args[field] === null || request.args[field] === "") {
      throw new ProtocolError("VALIDATION_ERROR", `${field} is required for command '${request.command}'`, validationDetails(request, spec, field));
    }
  }
  validateKnownArgs(request, spec);
  validateAndNormalizeElementRef(request, spec);
  validateRequiredOneOf(request, spec);
  if (request.command === "set_checked" && typeof request.args.checked !== "boolean") {
    throw new ProtocolError("VALIDATION_ERROR", "checked must be a boolean for command 'set_checked'", { field: "checked" });
  }
  if (request.command === "upload" && !Array.isArray(request.args.files)) {
    throw new ProtocolError("VALIDATION_ERROR", "files must be an array for command 'upload'", { field: "files" });
  }
  validateOptionalStringArg(request, spec, "filter", [
    "click_probe",
    "network_start",
    "network_list"
  ]);
  validateOptionalBooleanArgs(request, ["force", "observeNewTab", "expectNewTab", "includeHeaders", "includeBody", "redactSensitive"]);
  validateOptionalNumberArgs(request, ["tabId", "clickCount", "waitMs", "maxRequests"]);
  return request;
}
function validateKnownArgs(request, spec) {
  const allowed = /* @__PURE__ */ new Set([...spec.required || [], ...spec.optional || []]);
  const provided = Object.keys(request.args || {});
  const unknown = provided.filter((field2) => !allowed.has(field2));
  if (!unknown.length) return;
  const field = unknown[0];
  let suggestion = nearestArgName(field, [...allowed]);
  const hints = [];
  if (suggestion) hints.push(`Unknown argument "${field}". Did you mean "${suggestion}"?`);
  if (request.command === "find_tab" && (field === "urlContains" || field === "titleContains")) {
    suggestion = field === "urlContains" ? "urlIncludes" : "titleIncludes";
    hints.unshift(`Use "${suggestion}" for find_tab substring matching.`);
  }
  if (request.command === "fill" && field === "text") {
    hints.unshift("Use args.value for fill. args.text is not part of the fill command protocol.");
  }
  if (request.command === "network_detail" && field === "index") {
    hints.unshift("Use args.requestId from network_list; numeric index is not part of the network_detail protocol.");
  }
  if (request.command === "click" && field === "text") {
    hints.unshift("click uses args.elementRef for snapshot @e references. To click visible text, call snapshot with args.textIncludes and args.maxElements, then click the returned @e id.");
  }
  if (request.command === "get_text" && field === "selectors") {
    hints.unshift("get_text accepts one optional args.selector for the text extraction scope. To find clickable targets by text, use snapshot with args.textIncludes.");
  }
  throw new ProtocolError("VALIDATION_ERROR", `Unknown argument '${field}' for command '${request.command}'`, {
    field,
    command: request.command,
    unknown,
    required: spec.required,
    optional: spec.optional || [],
    validArgs: [...allowed],
    provided,
    suggestion,
    hints,
    hint: hints[0] || void 0
  });
}
function validateAndNormalizeElementRef(request, spec) {
  if (!Object.prototype.hasOwnProperty.call(request.args || {}, "elementRef")) return;
  const value = request.args.elementRef;
  if (typeof value !== "string" || value === "") {
    throw new ProtocolError("VALIDATION_ERROR", `elementRef must be a non-empty string for command '${request.command}'`, {
      ...validationDetails(request, spec, "elementRef"),
      expectedType: "string",
      actualType: Array.isArray(value) ? "array" : typeof value,
      hint: 'Run snapshot and pass an element id such as {"elementRef":"@e1jm0sbb_1"}.'
    });
  }
  if (!ELEMENT_REF_PATTERN.test(value)) {
    throw new ProtocolError("VALIDATION_ERROR", `elementRef must be an @e<structureId>_<revision> reference for command '${request.command}'`, {
      ...validationDetails(request, spec, "elementRef"),
      expectedFormat: "@e<structureId>_<revision>",
      value,
      hint: 'Run snapshot and pass the returned element id, for example {"elementRef":"@e1jm0sbb_1"}. Use args.selector only for CSS fallback.'
    });
  }
  const selector = request.args.selector;
  if (selector !== void 0 && selector !== null && selector !== "" && selector !== value) {
    throw new ProtocolError("VALIDATION_ERROR", `elementRef and selector cannot target different elements for command '${request.command}'`, {
      ...validationDetails(request, spec, "elementRef"),
      elementRef: value,
      selector,
      hint: "Use either args.elementRef for a snapshot @e reference or args.selector for a CSS fallback, not both with different values."
    });
  }
  request.args.selector = value;
}
function validateRequiredOneOf(request, spec) {
  const fields = spec.requiredOneOf || [];
  if (!fields.length) return;
  if (fields.some((field) => request.args[field] !== void 0 && request.args[field] !== null && request.args[field] !== "")) return;
  throw new ProtocolError("VALIDATION_ERROR", `${fields.join(" or ")} is required for command '${request.command}'`, {
    ...validationDetails(request, spec, fields[0]),
    requiredOneOf: fields,
    hint: "Prefer args.elementRef with a fresh snapshot @e reference. Use args.selector only for CSS fallback."
  });
}
function nearestArgName(field, candidates) {
  let best = null;
  let bestDistance = Infinity;
  for (const candidate of candidates) {
    const distance = levenshtein(String(field), String(candidate));
    if (distance < bestDistance) {
      best = candidate;
      bestDistance = distance;
    }
  }
  const maxDistance = Math.max(2, Math.floor(String(field).length / 3));
  return bestDistance <= maxDistance ? best : null;
}
function levenshtein(a, b) {
  const rows = Array.from({ length: a.length + 1 }, (_, i) => [i]);
  for (let j = 1; j <= b.length; j += 1) rows[0][j] = j;
  for (let i = 1; i <= a.length; i += 1) {
    for (let j = 1; j <= b.length; j += 1) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      rows[i][j] = Math.min(
        rows[i - 1][j] + 1,
        rows[i][j - 1] + 1,
        rows[i - 1][j - 1] + cost
      );
    }
  }
  return rows[a.length][b.length];
}
function validateOptionalStringArg(request, spec, field, commands) {
  if (!commands.includes(request.command)) return;
  if (!Object.prototype.hasOwnProperty.call(request.args || {}, field)) return;
  const value = request.args[field];
  if (value === void 0 || value === null || value === "") return;
  if (typeof value === "string") return;
  throw new ProtocolError("VALIDATION_ERROR", `${field} must be a string for command '${request.command}'`, {
    ...validationDetails(request, spec, field),
    expectedType: "string",
    actualType: Array.isArray(value) ? "array" : typeof value,
    hint: `Use args.${field} as a URL substring string, for example {"${field}":"/api/"}, or omit it for no filtering.`
  });
}
function validateOptionalBooleanArgs(request, fields) {
  for (const field of fields) {
    if (!Object.prototype.hasOwnProperty.call(request.args || {}, field)) continue;
    const value = request.args[field];
    if (typeof value === "boolean") continue;
    throw new ProtocolError("VALIDATION_ERROR", `${field} must be a boolean for command '${request.command}'`, {
      field,
      command: request.command,
      expectedType: "boolean",
      actualType: Array.isArray(value) ? "array" : typeof value
    });
  }
}
function validateOptionalNumberArgs(request, fields) {
  for (const field of fields) {
    if (!Object.prototype.hasOwnProperty.call(request.args || {}, field)) continue;
    const value = request.args[field];
    if (typeof value === "number" && Number.isFinite(value)) continue;
    throw new ProtocolError("VALIDATION_ERROR", `${field} must be a finite number for command '${request.command}'`, {
      field,
      command: request.command,
      expectedType: "number",
      actualType: Array.isArray(value) ? "array" : typeof value
    });
  }
}
function validationDetails(request, spec, field) {
  const details = {
    field,
    command: request.command,
    required: spec.required,
    requiredOneOf: spec.requiredOneOf || [],
    optional: spec.optional || [],
    example: spec.example || null,
    provided: Object.keys(request.args || {})
  };
  const hints = [];
  if (request.command === "fill" && field === "value" && request.args && Object.prototype.hasOwnProperty.call(request.args, "text")) {
    hints.push("Use args.value for fill. args.text is not part of the fill command protocol.");
    details.receivedAlias = "text";
    details.expectedAlias = "value";
  }
  if (request.command === "network_detail" && Object.prototype.hasOwnProperty.call(request.args || {}, "index")) {
    hints.push("Use args.requestId from network_list; numeric index is not part of the network_detail protocol.");
  }
  if (request.command === "observe_diff" && field === "baselineId") {
    hints.push("Run observe_start first, then pass the returned baselineId to observe_diff.");
  }
  if (request.command === "click" && Object.prototype.hasOwnProperty.call(request.args || {}, "text")) {
    hints.push("click uses args.elementRef for snapshot @e references. Run snapshot and click a returned element id; semantic click_text is deferred.");
  }
  if (hints.length) {
    details.hints = hints;
    details.hint = hints[0];
  }
  return details;
}
function protocolErrorFrom(err, fallbackCode = "BACKEND_ERROR") {
  if (err instanceof ProtocolError) return err;
  const message = err?.message || String(err);
  if (/observation baseline not found|baseline not found/i.test(message)) {
    return new ProtocolError("NOT_FOUND", message, {
      nextSteps: [
        "Run observe_start again for the active session tab.",
        "If navigation occurred, create a new baseline before retrying observe_diff."
      ]
    }, true);
  }
  if (/element not found|no element/i.test(message)) {
    return new ProtocolError("NOT_FOUND", message, {
      nextSteps: [
        "Run snapshot again and use a fresh @e<structureId>_<revision> reference.",
        "If the page changed, wait_for the target text or selector before retrying."
      ]
    }, true);
  }
  if (/no active tab/i.test(message)) {
    return new ProtocolError("BACKEND_UNAVAILABLE", message, {
      nextSteps: [
        "Run navigate to open a tab in this session, or find_tab with attach=true to reuse an existing tab."
      ]
    }, true);
  }
  if (/extension.*not connected|not connected|disconnected/i.test(message)) {
    return new ProtocolError("BACKEND_UNAVAILABLE", message, {
      nextSteps: [
        "Run doctor --json to confirm daemon and extension readiness.",
        "Reload the Chrome extension if doctor reports extension_connected=false."
      ]
    }, true);
  }
  const retryable = /timeout|temporarily/i.test(message);
  const code = /timeout/i.test(message) ? "TIMEOUT" : retryable ? "BACKEND_UNAVAILABLE" : fallbackCode;
  const details = retryable ? {
    nextSteps: ["Retry after wait_for or increase timeoutMs if the page is still loading."]
  } : void 0;
  return new ProtocolError(code, message, details, retryable);
}
function createResultEnvelope(request, { ok, backend = "extension", tab = null, data = null, artifacts = [], error = null, diagnostics = null, startedAt, endedAt = (/* @__PURE__ */ new Date()).toISOString() }) {
  const started = startedAt || endedAt;
  return {
    id: request.id,
    ok,
    command: request.command,
    backend,
    session: request.session,
    tab,
    artifacts,
    startedAt: started,
    endedAt,
    durationMs: Math.max(0, new Date(endedAt).getTime() - new Date(started).getTime()),
    data,
    error,
    diagnostics
  };
}
function mapNetworkCommand(command, args) {
  switch (command) {
    case "network_start":
      return { command: "network", args: { ...args, cmd: "start" } };
    case "network_list":
      return { command: "network", args: { ...args, cmd: "list" } };
    case "network_detail":
      return { command: "network", args: { ...args, cmd: "detail" } };
    case "network_stop":
      return { command: "network", args: { ...args, cmd: "stop" } };
    default:
      return { command, args };
  }
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  CLI_CAPABILITIES,
  COMMANDS,
  DAEMON_CAPABILITIES,
  EXTENSION_CAPABILITY_HINTS,
  LEGACY_ACTION_ALIASES,
  PROTOCOL_VERSION,
  ProtocolError,
  RUNTIME_SCHEMA_VERSION,
  createResultEnvelope,
  mapNetworkCommand,
  normalizeCommand,
  normalizeRequest,
  protocolErrorFrom,
  validateRequest
});
