'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.resolve(__dirname, '..');
const generatedExtensionRoot = 'skills/browser-control/extension';

function extensionPath(file) {
  return path.posix.join(generatedExtensionRoot, file);
}

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

test('extension build emits declared Chrome-loadable output from src/extension', () => {
  const result = spawnSync(process.execPath, [path.join(root, 'scripts', 'build-extension.mjs')], {
    cwd: root,
    encoding: 'utf8'
  });
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.match(result.stdout, /extension build ok/);

  for (const relativePath of [
    extensionPath('manifest.json'),
    extensionPath('service-worker.js'),
    extensionPath('content.js'),
    extensionPath('popup.html'),
    extensionPath('popup.js'),
    extensionPath('options.html'),
    extensionPath('options.js'),
    extensionPath('icons/icon16.png'),
    extensionPath('icons/icon48.png'),
    extensionPath('icons/icon128.png')
  ]) {
    assert.equal(fs.existsSync(path.join(root, relativePath)), true, `${relativePath} should exist`);
  }
});

test('generated extension manifest preserves source manifest semantics', () => {
  const source = JSON.parse(read('src/extension/manifest.json'));
  const generated = JSON.parse(read(extensionPath('manifest.json')));
  assert.deepEqual(generated, source);
  assert.equal(generated.background.service_worker, 'service-worker.js');
  assert.deepEqual(generated.content_scripts[0].js, ['content.js']);
  assert.equal(generated.action.default_popup, 'popup.html');
  assert.equal(generated.options_page, 'options.html');
});

test('generated runtime entrypoints remain classic scripts without runtime module imports', () => {
  for (const relativePath of [
    extensionPath('service-worker.js'),
    extensionPath('content.js'),
    extensionPath('popup.js'),
    extensionPath('options.js')
  ]) {
    const source = read(relativePath);
    const withoutComments = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
    assert.doesNotMatch(withoutComments, /^\s*import\s/m, relativePath);
    assert.doesNotMatch(withoutComments, /^\s*export\s/m, relativePath);
    assert.doesNotMatch(withoutComments, /\bimport\s*\(/, relativePath);
    assert.match(source, /Generated by scripts\/build-extension\.mjs from src\/extension/);
  }
});


test('generated executeScript page runtime functions are isolated VM-callable', async () => {
  const source = read(extensionPath('service-worker.js'));
  const cases = [
    {
      name: 'resolveClickTargetForCdp',
      args: ['#missing', {}],
      assertResult: result => assert.equal(result.error, 'Element not found: #missing')
    },
    {
      name: 'performUpload',
      args: ['#file', ['a.txt']],
      setup: sandbox => {
        sandbox.document.querySelector = selector => selector === '#file'
          ? { tagName: 'INPUT', type: 'file', accept: '.txt', multiple: true }
          : null;
      },
      assertResult: result => {
        assert.equal(result.status, 'needs_native_picker');
        assert.equal(result.accept, '.txt');
        assert.equal(result.multiple, true);
      }
    },
    {
      name: 'getAccessibilitySnapshot',
      args: [],
      assertResult: result => {
        assert.equal(Array.isArray(result.elements), true);
        assert.equal(result.elements.length, 0);
      }
    },
    {
      name: 'performClick',
      args: ['#missing', {}],
      assertResult: result => assert.equal(result.error, 'Element not found: #missing')
    },
    {
      name: 'performFill',
      args: ['#missing', 'x', {}],
      assertResult: result => assert.equal(result.error, 'Element not found: #missing')
    },
    {
      name: 'performPress',
      args: ['Enter', '#missing', {}],
      assertResult: result => assert.equal(result.error, 'Element not found: #missing')
    },
    {
      name: 'performSelectOption',
      args: ['#missing', 'x'],
      assertResult: result => assert.equal(result.error, 'Element not found: #missing')
    },
    {
      name: 'performSetChecked',
      args: ['#missing', true],
      assertResult: result => assert.equal(result.error, 'Element not found: #missing')
    },
    {
      name: 'performWaitFor',
      args: [{ selector: '#missing', timeoutMs: 0 }],
      assertResult: result => assert.match(result.error, /Timed out waiting for #missing/)
    },
    {
      name: 'performEvaluate',
      args: ['1 + 1'],
      assertResult: result => assert.equal(result.result, 2)
    },
    {
      name: 'captureViewportTextObservation',
      args: [{}],
      assertResult: result => assert.equal(result.visibleText, '')
    }
  ];

  for (const testCase of cases) {
    const fnSource = extractFunction(source, testCase.name);
    assert.doesNotMatch(fnSource, /\bimport\b|\bexport\b/, testCase.name);
    const sandbox = createIsolatedPageSandbox();
    testCase.setup?.(sandbox);
    vm.createContext(sandbox);
    const fn = vm.runInContext(`(${fnSource})`, sandbox);
    const result = await fn(...testCase.args);
    testCase.assertResult(result);
  }
});

test('snapshot runtime emits compact schema, deterministic depth, direct text, and redacts sensitive values', async () => {
  const source = read(extensionPath('service-worker.js'));
  const fnSource = extractFunction(source, 'getAccessibilitySnapshot');
  const sandbox = createSnapshotSandbox();
  vm.createContext(sandbox);
  const getSnapshot = vm.runInContext(`(${fnSource})`, sandbox);

  const full = await getSnapshot({});
  assert.equal(full.schemaVersion, 2);
  assert.equal(full.semantics, 'compact-dom-v2');
  assert.equal(full.filters.maxDepth, null);
  assert.equal(full.stats.scanned >= 7, true);
  assert.equal(full.stats.returned, full.elements.length);
  assert.equal(full.totalBeforeFilter, full.stats.scanned);

  const panel = full.elements.find(element => element.testId === 'panel');
  assert.equal(panel.visibleText, 'Panel direct text');
  assert.doesNotMatch(panel.visibleText || '', /Nested descendant text/);

  const button = full.elements.find(element => element.tag === 'button');
  assert.equal(button.name, 'Nested descendant text');
  assert.equal(button.visibleText, 'Nested descendant text');
  assert.match(button.id, /^@e\d+$/);

  const token = full.elements.find(element => element.testId === 'token-input');
  assert.equal(token.attributes.value, '[redacted]');
  assert.equal(token.attributes.valueLength, 'super-secret-token'.length);
  assert.equal(token.attributes.redacted, true);
  assert.doesNotMatch(JSON.stringify(token), /super-secret-token/);

  const shallow = await getSnapshot({ maxDepth: 1 });
  assert.equal(shallow.elements.some(element => element.testId === 'panel'), true);
  assert.equal(shallow.elements.some(element => element.tag === 'button'), false);

  const buttons = await getSnapshot({ roles: ['button'], maxElements: 1 });
  assert.equal(buttons.elements.length, 1);
  assert.equal(buttons.stats.matched >= 1, true);
  assert.equal(buttons.elements.every(element => element.role === 'button'), true);
  assert.notEqual(buttons.elements[0].id, button.id);

  const assignedIds = sandbox.document
    .querySelectorAll('[data-agent-id^="@e"]')
    .map(element => element.getAttribute('data-agent-id'));
  assert.equal(new Set(assignedIds).size, assignedIds.length);
  assert.equal(
    sandbox.document.querySelector(`[data-agent-id="${buttons.elements[0].id}"]`),
    sandbox.fixture.button
  );
});

function createIsolatedPageSandbox() {
  class FakeEvent {
    constructor(type, init = {}) {
      this.type = type;
      Object.assign(this, init);
    }
  }

  const emptyRect = { x: 0, y: 0, left: 0, top: 0, right: 0, bottom: 0, width: 0, height: 0 };
  const body = {
    nodeType: 1,
    tagName: 'BODY',
    id: '',
    className: '',
    textContent: '',
    getBoundingClientRect() { return emptyRect; },
    getAttribute() { return null; },
    hasAttribute() { return false; },
    closest() { return null; },
    setAttribute() {}
  };
  const document = {
    title: '',
    activeElement: null,
    body,
    documentElement: { ...body, clientWidth: 1024, clientHeight: 768 },
    querySelector() { return null; },
    querySelectorAll() { return []; },
    elementFromPoint() { return null; },
    createTreeWalker() {
      return {
        currentNode: null,
        nextNode() { return false; }
      };
    },
    createRange() {
      return {
        selectNodeContents() {},
        getClientRects() { return []; },
        detach() {}
      };
    }
  };
  return {
    document,
    window: {
      innerWidth: 1024,
      innerHeight: 768,
      scrollX: 0,
      scrollY: 0,
      screenX: 0,
      screenY: 0,
      location: { href: 'about:blank' },
      getSelection: () => null,
      getComputedStyle: () => ({ display: 'block', visibility: 'visible', opacity: '1' })
    },
    Node: { ELEMENT_NODE: 1, TEXT_NODE: 3 },
    NodeFilter: { SHOW_ELEMENT: 1, SHOW_TEXT: 4, FILTER_ACCEPT: 1, FILTER_REJECT: 2, FILTER_SKIP: 3 },
    CSS: { escape: value => String(value) },
    Event: FakeEvent,
    InputEvent: FakeEvent,
    KeyboardEvent: FakeEvent,
    MouseEvent: FakeEvent,
    PointerEvent: FakeEvent,
    HTMLInputElement: class {},
    HTMLTextAreaElement: class {},
    HTMLSelectElement: class {},
    setTimeout
  };
}

function createSnapshotSandbox() {
  class FakeElement {
    constructor(tagName, attrs = {}, options = {}) {
      this.nodeType = 1;
      this.tagName = tagName.toUpperCase();
      this.attrs = { ...attrs };
      this.childNodes = [];
      this.children = [];
      this.parentElement = null;
      this.value = options.value || '';
      this.checked = options.checked || false;
      this.disabled = options.disabled || false;
      this.onclick = options.onclick || null;
      this.rect = options.rect || { x: 0, y: 0, left: 0, top: 0, right: 120, bottom: 24, width: 120, height: 24 };
      this.style = options.style || { display: 'block', visibility: 'visible' };
      this.options = options.options || [];
      this.selectedIndex = options.selectedIndex || 0;
      if (options.text) this.childNodes.push({ nodeType: 3, textContent: options.text });
      for (const child of options.children || []) this.appendChild(child);
    }
    get id() { return this.attrs.id || ''; }
    get className() { return this.attrs.class || ''; }
    get textContent() {
      return this.childNodes.map(child => child.textContent || '').join('');
    }
    get innerText() {
      return this.textContent;
    }
    get alt() {
      return this.attrs.alt || '';
    }
    getAttribute(name) {
      return Object.prototype.hasOwnProperty.call(this.attrs, name) ? this.attrs[name] : null;
    }
    setAttribute(name, value) {
      this.attrs[name] = String(value);
    }
    appendChild(child) {
      child.parentElement = this;
      this.children.push(child);
      this.childNodes.push(child);
    }
    getBoundingClientRect() {
      return this.rect;
    }
  }

  const button = new FakeElement('button', {}, { text: 'Nested descendant text' });
  const inline = new FakeElement('span', {}, { text: 'inline cell text' });
  const cell = new FakeElement('td', { 'data-testid': 'cell' }, { text: 'Cell direct ', children: [inline] });
  const tokenInput = new FakeElement('input', {
    type: 'text',
    name: 'api_token',
    placeholder: 'Token',
    'data-testid': 'token-input'
  }, { value: 'super-secret-token' });
  const panel = new FakeElement('div', { 'data-testid': 'panel' }, {
    text: 'Panel direct text',
    children: [button, cell, tokenInput]
  });
  const username = new FakeElement('input', {
    type: 'text',
    name: 'username',
    placeholder: 'Username',
    'data-testid': 'username-input'
  }, { value: 'alice' });
  const hidden = new FakeElement('div', { 'data-testid': 'offscreen' }, {
    text: 'Offscreen',
    rect: { x: 0, y: 900, left: 0, top: 900, right: 120, bottom: 924, width: 120, height: 24 }
  });
  const body = new FakeElement('body', {}, { children: [panel, username, hidden] });

  function allElements() {
    const nodes = [];
    function visit(node) {
      for (const child of node.children || []) {
        nodes.push(child);
        visit(child);
      }
    }
    visit(body);
    return nodes;
  }

  const document = {
    title: 'Snapshot Fixture',
    body,
    querySelector(selector) {
      if (!selector.startsWith('[data-agent-id="')) return null;
      const id = selector.slice('[data-agent-id="'.length, -2);
      return allElements().find(element => element.getAttribute('data-agent-id') === id) || null;
    },
    querySelectorAll(selector) {
      if (selector !== '[data-agent-id^="@e"]') return [];
      return allElements().filter(element => /^@e\d+$/.test(element.getAttribute('data-agent-id') || ''));
    },
    createTreeWalker(root, _show, filter) {
      const nodes = [];
      function visit(node) {
        for (const child of node.children || []) {
          const decision = filter.acceptNode(child);
          if (decision === 1) {
            nodes.push(child);
            visit(child);
          } else if (decision === 3) {
            visit(child);
          }
        }
      }
      visit(root);
      let index = -1;
      return {
        currentNode: null,
        nextNode() {
          index += 1;
          if (index >= nodes.length) return false;
          this.currentNode = nodes[index];
          return true;
        }
      };
    }
  };

  return {
    document,
    fixture: { button },
    window: {
      innerWidth: 800,
      innerHeight: 600,
      location: { href: 'https://example.test/snapshot' },
      getComputedStyle: element => element.style
    },
    Node: { ELEMENT_NODE: 1, TEXT_NODE: 3 },
    NodeFilter: { SHOW_ELEMENT: 1, FILTER_ACCEPT: 1, FILTER_REJECT: 2, FILTER_SKIP: 3 },
    CSS: { escape: value => String(value) },
    Array,
    String,
    Number,
    RegExp,
    Math
  };
}

function extractFunction(source, name) {
  const start = source.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `${name} source should exist`);
  const signatureMatch = new RegExp(`function\\s+${name}\\s*\\([^]*?\\)\\s*\\{`).exec(source.slice(start));
  assert.notEqual(signatureMatch, null, `${name} signature should include a body`);
  const bodyStart = start + signatureMatch[0].length - 1;
  let depth = 0;
  for (let index = bodyStart; index < source.length; index += 1) {
    const char = source[index];
    if (char === '{') depth += 1;
    if (char === '}') depth -= 1;
    if (depth === 0) return source.slice(start, index + 1).trim();
  }
  assert.fail(`${name} body should end`);
}

test('extension build script uses declared output allowlist', () => {
  const source = read('scripts/build-extension.mjs');
  assert.match(source, /declaredOutputs/);
  assert.match(source, /Refusing to write undeclared extension output/);
  assert.doesNotMatch(source, /rmSync\([^)]*outRoot[^)]*recursive:\s*true/s);
});
