// Generated by scripts/build-extension.mjs from src/extension/**.
// Do not edit this file directly; edit src/extension and run npm run build:extension.
"use strict";
(() => {
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __commonJS = (cb, mod) => function __require() {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  };

  // src/extension/ui/options.ts
  var require_options = __commonJS({
    "src/extension/ui/options.ts"() {
      var defaults = {
        daemonUrl: "ws://127.0.0.1:10087/ws",
        requestTimeout: 3e4,
        confirmActions: true
      };
      async function loadSettings() {
        const stored = await chrome.storage.sync.get(defaults);
        document.getElementById("daemonUrl").value = stored.daemonUrl;
        document.getElementById("requestTimeout").value = stored.requestTimeout;
        document.getElementById("confirmActions").checked = stored.confirmActions;
      }
      async function saveSettings() {
        const settings = {
          daemonUrl: document.getElementById("daemonUrl").value || defaults.daemonUrl,
          requestTimeout: parseInt(document.getElementById("requestTimeout").value) || defaults.requestTimeout,
          confirmActions: document.getElementById("confirmActions").checked
        };
        await chrome.storage.sync.set(settings);
        const msg = document.getElementById("savedMsg");
        msg.classList.add("show");
        setTimeout(() => msg.classList.remove("show"), 2e3);
      }
      document.getElementById("btnSave").addEventListener("click", saveSettings);
      loadSettings();
    }
  });
  require_options();
})();
