// Generated by scripts/build-extension.mjs from src/extension/**.
// Do not edit this file directly; edit src/extension and run npm run build:extension.
"use strict";
(() => {
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __commonJS = (cb, mod) => function __require() {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  };

  // src/extension/ui/popup.ts
  var require_popup = __commonJS({
    "src/extension/ui/popup.ts"() {
      var el = (id) => document.getElementById(id);
      async function refreshStatus() {
        try {
          const status = await chrome.runtime.sendMessage({ type: "getStatus" });
          updateUI(status);
        } catch {
          updateUI({ connected: false, sessionCount: 0, activeSessions: [], tabCount: 0 });
        }
      }
      function updateUI(status) {
        const connected = status.connected;
        el("daemonDot").className = "dot " + (connected ? "green" : "red");
        el("daemonStatus").textContent = connected ? "connected" : "disconnected";
        el("wsDot").className = "dot " + (connected ? "green" : "yellow");
        el("wsStatus").textContent = connected ? "open" : "closed";
        el("sessionCount").textContent = String(status.sessionCount || 0);
        el("tabCount").textContent = String(status.tabCount || 0);
        const container = el("sessionList");
        if (status.activeSessions && status.activeSessions.length > 0) {
          container.innerHTML = status.activeSessions.map((s) => `<span class="session-tag">\u{1F916} ${escapeHtml(s)}</span>`).join("");
        } else {
          container.innerHTML = "";
        }
        el("btnConnect").disabled = connected;
        el("btnDisconnect").disabled = !connected;
      }
      function escapeHtml(str) {
        const div = document.createElement("div");
        div.textContent = str;
        return div.innerHTML;
      }
      el("btnConnect").addEventListener("click", async () => {
        await chrome.runtime.sendMessage({ type: "connect" });
        setTimeout(refreshStatus, 500);
      });
      el("btnDisconnect").addEventListener("click", async () => {
        await chrome.runtime.sendMessage({ type: "disconnect" });
        setTimeout(refreshStatus, 500);
      });
      refreshStatus();
      setInterval(refreshStatus, 5e3);
    }
  });
  require_popup();
})();
