#!/usr/bin/env node
import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outFile = path.join(root, 'skills', 'browser-control', 'scripts', 'daemon.js');
const vendorWsRoot = path.join(root, 'skills', 'browser-control', 'scripts', 'vendor', 'ws');

fs.mkdirSync(path.dirname(outFile), { recursive: true });

await build({
  entryPoints: [path.join(root, 'src', 'daemon', 'daemon-cli.ts')],
  outfile: outFile,
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'cjs',
  external: [
    'node:*'
  ],
  legalComments: 'none',
  logLevel: 'silent',
  banner: {
    js: [
      '// Generated by scripts/build-daemon.mjs from src/daemon/**.',
      '// Do not edit this file directly; edit src/daemon and run npm run build:daemon.'
    ].join('\n')
  }
});

fs.chmodSync(outFile, 0o755);
fs.rmSync(vendorWsRoot, { recursive: true, force: true });

console.log(`daemon build ok: bundled ${path.relative(root, outFile)} and removed ${path.relative(root, vendorWsRoot)}/`);
